/// ไอคอนทั้งชุดของแอป — เพิ่ม/เปลี่ยนที่นี่ที่เดียว หน้าอื่นห้าม import จาก lucide-react ตรง ๆ
export {
  LayoutDashboard as IconDashboard,
  Package as IconProduct,
  PackagePlus as IconStockIn,
  PackageMinus as IconStockOut,
  ChartColumn as IconReports,
  Users as IconUsers,
  Settings as IconSettings,
  Search as IconSearch,
  Plus as IconPlus,
  Pencil as IconEdit,
  Trash2 as IconTrash,
  TriangleAlert as IconWarning,
  LogOut as IconLogout,
  ChevronDown as IconChevronDown,
  ArrowDownToLine as IconArrowIn,
  ArrowUpFromLine as IconArrowOut,
  Boxes as IconBoxes,
  Wallet as IconWallet,
  Loader2 as IconSpinner,
  CircleUser as IconUser,
  Mail as IconMail,
  LockKeyhole as IconLock,
  ArrowLeft as IconBack,
  CircleCheck as IconCheck,
} from "lucide-react"
